modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="everpotion"
version="${file.jarVersion}"
displayName="EverPotion"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/everpotion"
description=""

[[dependencies.everpotion]]
    modId="kiwi"
    mandatory=true
    versionRange="[2.7.1, 2.11)"
    ordering="BEFORE"
    side="BOTH"
