modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
modId="everpotion"
version="${file.jarVersion}"
displayName="EverPotion"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/everpotion"
description=""

[[dependencies.everpotion]]
    modId="kiwi"
    mandatory=true
    versionRange="[3.1.0, 3.7)"
    ordering="BEFORE"
    side="BOTH"
