modLoader="javafml"
loaderVersion="[33,)"
license="MIT"

[[mods]]
modId="everpotion"
version="${file.jarVersion}"
displayName="EverPotion"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/everpotion"
description=""

[[dependencies.everpotion]]
    modId="kiwi"
    mandatory=true
    versionRange="[3.3, 3.9)"
    ordering="BEFORE"
    side="BOTH"
